# Generated by Django 3.1.7 on 2021-04-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210426_0747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='countFriends',
        ),
    ]
